# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:
vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.79722275 0.69499419 0.89657822 0.62219935 0.87791835]
 [0.84262257 0.41993415 0.54186589 0.24687494 0.13403484]
 [0.89972225 0.72795285 0.55208793 0.72054337 0.68884893]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]

[[ 1.15601659 -0.03705332 -1.55463105 -0.9367318   2.05231331]
 [-0.22921226  0.33226061  0.3371321   0.23970124  1.10892502]
 [-0.94874958 -2.88686055 -1.21444653 -0.25821163  1.10207157]
 [ 2.08487599  1.55572158 -1.888009   -1.57331505 -0.30195061]
 [ 1.45325111  0.14058749  1.19574066 -1.89834959 -0.07656611]
 [-1.09096625 -0.8899673   0.48588796 -1.47284533  0.35610287]
 [-1.5271853   0.04266859  2.31906006 -0.87135291 -1.35711202]
 [-0.77081519 -0.23389945  0.38086826 -1.58760146  1.55038027]
 [-0.14468112 -0.85108683  0.37103356  1.70891691  0.9537487 ]
 [ 0.40259713  0.82485511 -0.31202305 -0.29892451  1.48750226]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.543798855117003
1.1909523067845837


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.09386148216436319
2.3190600645978905


In [ ]:
# break here for next video!

In [14]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.67484578 -2.47762314  1.7575114   0.72411968  1.31165573 -1.07452566
 -0.43648419 -0.2262583   0.56926804  0.03414228 -2.29033813 -0.19723797
 -0.85041241  0.16572374  0.26811943 -0.11563363  0.14505201  0.50215215
  0.28388068]
-0.43648419263154487


In [15]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.31165573 -1.07452566 -0.43648419 -0.2262583   0.56926804]


In [16]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.67484578  0.72411968 -0.43648419  0.03414228 -0.85041241]


In [17]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.79722275 0.69499419 0.89657822 0.62219935 0.87791835]
 [0.84262257 0.41993415 0.54186589 0.24687494 0.13403484]
 [0.89972225 0.72795285 0.55208793 0.72054337 0.68884893]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]
0.5418658943732779
0.5418658943732779


In [18]:
print(rand_mat[0:2,1:3])

[[0.69499419 0.89657822]
 [0.41993415 0.54186589]]


In [19]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.67484578 -2.47762314  1.7575114   0.72411968  1.31165573 -1.07452566
 -0.43648419 -0.2262583   0.56926804  0.03414228 -2.29033813 -0.19723797
 -0.85041241  0.16572374  0.26811943 -0.11563363  0.14505201  0.50215215
  0.28388068]

[-0.67484578 -2.47762314  1.7575114   4.          4.         -1.07452566
 -0.43648419 -0.2262583   0.56926804  0.03414228 -2.29033813 -0.19723797
 -0.85041241  0.16572374  0.26811943 -0.11563363  0.14505201  0.50215215
  0.28388068]

[-0.67484578 -2.47762314  1.7575114   1.          2.         -1.07452566
 -0.43648419 -0.2262583   0.56926804  0.03414228 -2.29033813 -0.19723797
 -0.85041241  0.16572374  0.26811943 -0.11563363  0.14505201  0.50215215
  0.28388068]


In [20]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.79722275 0.69499419 0.89657822 0.62219935 0.87791835]
 [0.84262257 0.41993415 0.54186589 0.24687494 0.13403484]
 [0.89972225 0.72795285 0.55208793 0.72054337 0.68884893]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]

[[0.79722275 0.69499419 0.89657822 0.62219935 0.87791835]
 [0.84262257 0.41993415 0.54186589 0.         0.        ]
 [0.89972225 0.72795285 0.55208793 0.         0.        ]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]


In [21]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[0.79722275 0.69499419 0.89657822]
 [0.84262257 0.41993415 0.54186589]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [22]:
print(rand_mat)

[[3.         3.         3.         0.62219935 0.87791835]
 [3.         3.         3.         0.         0.        ]
 [0.89972225 0.72795285 0.55208793 0.         0.        ]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]


In [23]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.62219935 0.87791835]
 [3.         3.         3.         0.         0.        ]
 [0.89972225 0.72795285 0.55208793 0.         0.        ]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]


In [ ]:
# break here for next video

In [24]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 1.12869129  1.01063695 -0.14063057  0.69793087 -1.02329522  0.20442222
 -2.29667789 -0.50289584  0.61344234  1.86953581  0.11466314 -0.23299373
  1.15625688  0.12980032  1.27861898]
[ True  True False  True False  True False False  True  True  True False
  True  True  True]
[1.12869129 1.01063695 0.69793087 0.20442222 0.61344234 1.86953581
 0.11466314 1.15625688 0.12980032 1.27861898]


In [25]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 1.15601659 -0.03705332 -1.55463105 -0.9367318   2.05231331]
 [-0.22921226  0.33226061  0.3371321   0.23970124  1.10892502]
 [-0.94874958 -2.88686055 -1.21444653 -0.25821163  1.10207157]
 [ 2.08487599  1.55572158 -1.888009   -1.57331505 -0.30195061]
 [ 1.45325111  0.14058749  1.19574066 -1.89834959 -0.07656611]
 [-1.09096625 -0.8899673   0.48588796 -1.47284533  0.35610287]
 [-1.5271853   0.04266859  2.31906006 -0.87135291 -1.35711202]
 [-0.77081519 -0.23389945  0.38086826 -1.58760146  1.55038027]
 [-0.14468112 -0.85108683  0.37103356  1.70891691  0.9537487 ]
 [ 0.40259713  0.82485511 -0.31202305 -0.29892451  1.48750226]]
[1.15601659 2.05231331 0.33226061 0.3371321  0.23970124 1.10892502
 1.10207157 2.08487599 1.55572158 1.45325111 0.14058749 1.19574066
 0.48588796 0.35610287 0.04266859 2.31906006 0.38086826 1.55038027
 0.37103356 1.70891691 0.9537487  0.40259713 0.82485511 1.48750226]


In [26]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 1.12869129  1.01063695 -0.14063057  0.69793087 -1.02329522  0.20442222
 -2.29667789 -0.50289584  0.61344234  1.86953581  0.11466314 -0.23299373
  1.15625688  0.12980032  1.27861898]

[-5.         -5.         -0.14063057 -5.         -1.02329522  0.20442222
 -2.29667789 -0.50289584 -5.         -5.          0.11466314 -0.23299373
 -5.          0.12980032 -5.        ]


In [27]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [28]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [29]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 1.15601659 -0.03705332 -1.55463105 -0.9367318   2.05231331]
 [-0.22921226  0.33226061  0.3371321   0.23970124  1.10892502]
 [-0.94874958 -2.88686055 -1.21444653 -0.25821163  1.10207157]
 [ 2.08487599  1.55572158 -1.888009   -1.57331505 -0.30195061]
 [ 1.45325111  0.14058749  1.19574066 -1.89834959 -0.07656611]
 [-1.09096625 -0.8899673   0.48588796 -1.47284533  0.35610287]
 [-1.5271853   0.04266859  2.31906006 -0.87135291 -1.35711202]
 [-0.77081519 -0.23389945  0.38086826 -1.58760146  1.55038027]
 [-0.14468112 -0.85108683  0.37103356  1.70891691  0.9537487 ]
 [ 0.40259713  0.82485511 -0.31202305 -0.29892451  1.48750226]]



In [30]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.62219935 0.87791835]
 [3.         3.         3.         0.         0.        ]
 [0.89972225 0.72795285 0.55208793 0.         0.        ]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]

[[ 1.15601659 -0.03705332 -1.55463105 -0.9367318   2.05231331]
 [-0.22921226  0.33226061  0.3371321   0.23970124  1.10892502]
 [-0.94874958 -2.88686055 -1.21444653 -0.25821163  1.10207157]
 [ 2.08487599  1.55572158 -1.888009   -1.57331505 -0.30195061]
 [ 1.45325111  0.14058749  1.19574066 -1.89834959 -0.07656611]
 [-1.09096625 -0.8899673   0.48588796 -1.47284533  0.35610287]
 [-1.5271853   0.04266859  2.31906006 -0.87135291 -1.35711202]
 [-0.77081519 -0.23389945  0.38086826 -1.58760146  1.55038027]
 [-0.14468112 -0.85108683  0.37103356  1.70891691  0.9537487 ]
 [ 0.40259713  0.82485511 -0.31202305 -0.29892451  1.48750226]]
[[3.         3.         3.         0.62219935 0.87791835]
 [3.         3.    

In [31]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.62219935 0.87791835]
 [3.         3.         3.         0.         0.        ]
 [0.89972225 0.72795285 0.55208793 0.         0.        ]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]

[[3.         3.         3.         0.62219935 0.87791835]
 [3.         3.         3.         0.         0.        ]
 [0.89972225 0.72795285 0.55208793 0.         0.        ]
 [0.38167603 0.23559377 0.76056444 0.28413083 0.09386148]
 [0.81135631 0.46206828 0.20109821 0.45468602 0.24653542]]
